[package]
name = "weather-rs"
version = "0.1.0"
authors = ["Vinícius Simões <vinicius.simoes95@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32"
colored = "1.6"
reqwest = "0.9.5"
chrono = { version = "0.4", features = ["serde"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
